/* 
 * File:   Interrupt_internal.h
 * Author: Unlimited
 *
 * Created on May 19, 2023, 7:19 PM
 */

#ifndef INTERRUPT_INTERNAL_H
#define	INTERRUPT_INTERNAL_H

/*Section includes */
#include "Interrupt_cfg.h" 

/*Section macros */

// interrupt for ADC 

#if ADC_ENABLE_FEATURE==ENABLE_FEATURE

#define AD_Converter_Interrupt_CLEAR_Flag_bit() (PIR1bits.ADIF=0)
#define AD_Converter_Interrupt_READ_Flag_bit() (PIR1bits.ADIF)

#define ADC_INRERRUPT_ENABLE()  (PIE1bits.ADIE=1)
#define ADC_INRERRUPT_DISABLE()  (PIE1bits.ADIE=0)

#if INTERRUPT_PRIORITY_FEATURE == ENABLE_FEATURE
#define ADC_ENABLE_HIGH_PRIORITY()    (IPR1bits.ADIP=1)
#define ADC_ENABLE_LOW_PRIORITY()    (IPR1bits.ADIP=0)

#endif
#endif


// INTERNAL INTERRUPT FOR TIMER0
#if TIMER0_ENABLE_FEATURE==ENABLE_FEATURE

#define TIMER0_Interrupt_CLEAR_Flag_bit() (INTCONbits.TMR0IF=0)
#define TIMER0_Interrupt_READ_Flag_bit() (INTCONbits.TMR0IF)

#define TIMER0_INRERRUPT_ENABLE()  (INTCONbits.TMR0IE=1)
#define TIMER0_INRERRUPT_DISABLE()  (INTCONbits.TMR0IE=0)

#if INTERRUPT_PRIORITY_FEATURE == ENABLE_FEATURE
#define TIMER0_ENABLE_HIGH_PRIORITY()    (INTCON2bits.TMR0IP=1)
#define TIMER0_ENABLE_LOW_PRIORITY()    (INTCON2bits.TMR0IP=0)

#endif
#endif

// INTERNAL INTERRUPT FOR TIMER1
#if TIMER1_ENABLE_FEATURE==ENABLE_FEATURE

#define TIMER1_Interrupt_CLEAR_Flag_bit() (PIR1bits.TMR1IF=0)
#define TIMER1_Interrupt_READ_Flag_bit() (PIR1bits.TMR1IF)

#define TIMER1_INRERRUPT_ENABLE()  (PIE1bits.TMR1IE=1)
#define TIMER1_INRERRUPT_DISABLE()  (PIE1bits.TMR1IE=0)

#if INTERRUPT_PRIORITY_FEATURE == ENABLE_FEATURE
#define TIMER1_ENABLE_HIGH_PRIORITY()    (IPR1bits.TMR1IP=1)
#define TIMER1_ENABLE_LOW_PRIORITY()    (IPR1bits.TMR1IP=0)

#endif
#endif


// INTERNAL INTERRUPT FOR TIMER2
#if TIMER2_ENABLE_FEATURE==ENABLE_FEATURE

#define TIMER2_Interrupt_CLEAR_Flag_bit() (PIR1bits.TMR2IF=0)
#define TIMER2_Interrupt_READ_Flag_bit() (PIR1bits.TMR2IF)

#define TIMER2_INRERRUPT_ENABLE()  (PIE1bits.TMR2IE=1)
#define TIMER2_INRERRUPT_DISABLE()  (PIE1bits.TMR2IE=0)

#if INTERRUPT_PRIORITY_FEATURE == ENABLE_FEATURE
#define TIMER2_ENABLE_HIGH_PRIORITY()    (IPR1bits.TMR2IP=1)
#define TIMER2_ENABLE_LOW_PRIORITY()    (IPR1bits.TMR2IP=0)

#endif
#endif

// INTERNAL INTERRUPT FOR TIMER3
#if TIMER3_ENABLE_FEATURE==ENABLE_FEATURE

#define TIMER3_Interrupt_CLEAR_Flag_bit() (PIR2bits.TMR3IF=0)
#define TIMER3_Interrupt_READ_Flag_bit() (PIR2bits.TMR3IF)

#define TIMER3_INRERRUPT_ENABLE()  (PIE2bits.TMR3IE=1)
#define TIMER3_INRERRUPT_DISABLE()  (PIE2bits.TMR3IE=0)

#if INTERRUPT_PRIORITY_FEATURE == ENABLE_FEATURE
#define TIMER2_ENABLE_HIGH_PRIORITY()    (IPR2bits.TMR3IP=1)
#define TIMER2_ENABLE_LOW_PRIORITY()    (IPR2bits.TMR3IP=0)

#endif
#endif


// INTERNAL INTERRUPT FOR CCP1
#if CCP1_ENABLE_FEATURE==ENABLE_FEATURE

#define CCP1_Interrupt_CLEAR_Flag_bit() (PIR1bits.CCP1IF=0)
#define CCP1_Interrupt_READ_Flag_bit() (PIR1bits.CCP1IF)

#define CCP1_INRERRUPT_ENABLE()  (PIE1bits.CCP1IE=1)
#define CCP1_INRERRUPT_DISABLE()  (PIE1bits.CCP1IE=0)

#if INTERRUPT_PRIORITY_FEATURE == ENABLE_FEATURE
#define CCP1_ENABLE_HIGH_PRIORITY()    (IPR1bits.CCP1IP=1)
#define CCP1_ENABLE_LOW_PRIORITY()    (IPR1bits.CCP1IP=0)

#endif
#endif


// INTERNAL INTERRUPT FOR CCP2
#if CCP2_ENABLE_FEATURE==ENABLE_FEATURE

#define CCP2_Interrupt_CLEAR_Flag_bit() (PIR2bits.CCP2IF=0)
#define CCP2_Interrupt_READ_Flag_bit() (PIR2bits.CCP2IF)

#define CCP2_INRERRUPT_ENABLE()  (PIE2bits.CCP2IE=1)
#define CCP2_INRERRUPT_DISABLE()  (PIE2bits.CCP2IE=0)

#if INTERRUPT_PRIORITY_FEATURE == ENABLE_FEATURE
#define CCP2_ENABLE_HIGH_PRIORITY()    (IPR2bits.CCP2IP=1)
#define CCP2_ENABLE_LOW_PRIORITY()    (IPR2bits.CCP2IP=0)

#endif
#endif

// INTERNAL INTERRUPT FOR MSSP
#if MSSP_ENABLE_FEATURE==ENABLE_FEATURE

#define MSSP_Interrupt_CLEAR_Flag_bit() (PIR1bits.SSPIF=0)
#define MSSP_Interrupt_READ_Flag_bit() (PIR1bits.SSPIF)
#define MSSP_BC_Interrupt_CLEAR_Flag_bit() (PIR2bits.BCLIF=0)
#define MSSP_BC_Interrupt_READ_Flag_bit() (PIR2bits.BCLIF)

#define MSSP_INRERRUPT_ENABLE()  (PIE1bits.SSPIE=1)
#define MSSP_INRERRUPT_DISABLE()  (PIE1bits.SSPIE=0)
#define MSSP_BC_INRERRUPT_ENABLE()  (PIE2bits.BCLIE=1)
#define MSSP_BC_INRERRUPT_DISABLE()  (PIE2bits.BCLIE=0)

#if INTERRUPT_PRIORITY_FEATURE == ENABLE_FEATURE
#define MSSP_ENABLE_HIGH_PRIORITY()    (IPR1bits.SSPIP=1)
#define MSSP_ENABLE_LOW_PRIORITY()    (IPR1bits.SSPIP=0)
#define MSSP_BC_ENABLE_HIGH_PRIORITY()    (IPR2bits.BCLIP=1)
#define MSSP_BC_ENABLE_LOW_PRIORITY()    (IPR2bits.BCLIP=0)

#endif
#endif



// INTERNAL INTERRUPT FOR EUSART
#if EUSART_ENABLE_FEATURE==ENABLE_FEATURE

#define EUSART_TX_Interrupt_CLEAR_Flag_bit() (PIR1bits.TXIF=0)
#define EUSART_TX_Interrupt_READ_Flag_bit() (PIR1bits.TXIF)
#define EUSART_RX_Interrupt_CLEAR_Flag_bit() (PIR1bits.RCIF=0)
#define EUSART_RX_Interrupt_READ_Flag_bit() (PIR1bits.RCIF)

#define EUSART_TX_INRERRUPT_ENABLE()  (PIE1bits.TXIE=1)
#define EUSART_TX_INRERRUPT_DISABLE()  (PIE1bits.TXIE=0)
#define EUSART_RX_INRERRUPT_ENABLE()  (PIE1bits.RCIE=1)
#define EUSART_RX_INRERRUPT_DISABLE()  (PIE1bits.RCIE=0)

#if INTERRUPT_PRIORITY_FEATURE == ENABLE_FEATURE
#define EUSART_TX_ENABLE_HIGH_PRIORITY()    (IPR1bits.TXIP=1)
#define EUSART_TX_ENABLE_LOW_PRIORITY()    (IPR1bits.TXIP=0)
#define EUSART_RX_ENABLE_HIGH_PRIORITY()    (IPR1bits.RCIP=1)
#define EUSART_RX_ENABLE_LOW_PRIORITY()    (IPR1bits.RCIP=0)

#endif
#endif
/*Section macros function  */

/*Section Data type */


/*Section function declaration  */

#endif	/* INTERRUPT_INTERNAL_H */

